swagger: "2.0"
info:
  description: "Doc Api SDIS 67"
  version: "1.0.0"
  title: "Swagger SDIS 67"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "SDIS67.swagger.io"
basePath: "/v2"
tags:
- name: "ticket"
  description: "Everything about your ticket"

schemes:
- "https"
- "http"
paths:
  /ticket/findByStatus/date:
    get:
      tags:
      - "ticket"
      summary: "Find Ticket By Status && Date"
      description: "Multiple status values can be provided with comma separated strings"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "status"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: true
        type: "array"
        items:
          type: "integer"
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          default: 0
      - name: "date"
        in: query
        type: string
        description: "A relative date range for the report, such as `Today` or `LastWeek`"
        collectionFormat: "multi"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ticket"
        "400":
          description: "Invalid status value"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  ticket:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      statuId:
        type: "integer"
        format: "int64"
      creatDate:
        type: "string"
        format: "date-time"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"